### ISSUE TITLE
404 when clicking on "Download the Class Documentation"

### ISSUE THREAD

**Issue by c-bebop** [networkit/networkit.github.io#2]
Dear NetworKit Homepage Administrators,

when clicking on "Download the Class Documentation" on https://networkit.github.io/ which leads to https://networkit.github.io/uploads/networkit-documentation.zip I get a 404 error.

I tried reloading several times but it won't work. Anything I do wrong or do you see the same issue?

**Comment by avdgrinten** [comment]
That links seems to be outdated and should be removed. Thank you for the report.

The documentation can be found online at: https://networkit.github.io/dev-docs/index.html
